language: ruby
before_install:
  - "echo 'gem: --no-rdoc --no-ri' > ~/.gemrc"
  - gem update --system
  - gem install bundler
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - jruby-9.0
  - jruby-9.1
  - jruby-9.2
  - jruby-head
  - rbx-3
script: bundle exec rake
