version: "{branch}-{build}"
build: off
clone_depth: 1

init:
  # Install Ruby 1.8.7
  - if %RUBY_VERSION%==187 (
      appveyor DownloadFile https://dl.bintray.com/oneclick/rubyinstaller/rubyinstaller-1.8.7-p374.exe -FileName C:\ruby_187.exe &
      C:\ruby_187.exe /verysilent /dir=C:\Ruby%RUBY_VERSION%
    )

  # Install Ruby head
  - if %RUBY_VERSION%==head (
      appveyor DownloadFile https://github.com/oneclick/rubyinstaller2/releases/download/rubyinstaller-head/rubyinstaller-head-x86.exe -FileName C:\head_x86.exe &
      C:\head_x86.exe /verysilent /dir=C:\Ruby%RUBY_VERSION%
    )
  - if %RUBY_VERSION%==head-x64 (
      appveyor DownloadFile https://github.com/oneclick/rubyinstaller2/releases/download/rubyinstaller-head/rubyinstaller-head-x64.exe -FileName C:\head_x64.exe &
      C:\head_x64.exe /verysilent /dir=C:\Ruby%RUBY_VERSION%
    )

  # Add Ruby to the path
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%

  # Install DevKit 4.5.2 for Ruby 1.8.7
  - if %RUBY_VERSION%==187 (
      mkdir C:\DevKit452 &
      appveyor DownloadFile https://dl.bintray.com/oneclick/rubyinstaller/defunct/DevKit-tdm-32-4.5.2-20110712-1620-sfx.exe -FileName C:\DevKit452\devkit_452.exe &
      cd C:\DevKit452 &
      7z x devkit_452.exe &
      ruby dk.rb init &
      ruby dk.rb install &
      cd C:\projects\bcrypt-ruby
    )

environment:
  matrix:
    - RUBY_VERSION: "head"
    - RUBY_VERSION: "head-x64"
    - RUBY_VERSION: "25"
    - RUBY_VERSION: "25-x64"
    - RUBY_VERSION: "24"
    - RUBY_VERSION: "24-x64"
    - RUBY_VERSION: "23"
    - RUBY_VERSION: "23-x64"
    - RUBY_VERSION: "22"
    - RUBY_VERSION: "22-x64"
    - RUBY_VERSION: "21"
    - RUBY_VERSION: "21-x64"
    - RUBY_VERSION: "200"
    - RUBY_VERSION: "200-x64"
    - RUBY_VERSION: "193"
    - RUBY_VERSION: "187"

install:
  - if %RUBY_VERSION%==187 (
      gem update --system 2.0.17 &
      C:\DevKit452\devkitvars.bat
    )
  - if %RUBY_VERSION%==head     ( gem install bundler )
  - if %RUBY_VERSION%==head-x64 ( gem install bundler )
  - bundle install

before_test:
  - ruby -v
  - gem -v

build_script:
  - bundle exec rake compile -rdevkit

test_script:
  - bundle exec rake spec
